{% set name = "finagg" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/finagg-{{ version }}.tar.gz
  sha256: bbce2df01a4045675805f17f8557361d1bafb428fd9555732b2c8a25a6b4b551

build:
  entry_points:
    - finagg = finagg.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64.0
    - setuptools-scm >=5
    - pip
  run:
    - python >=3.10
    - beautifulsoup4 ==4.*
    - click ==8.*
    - pandas ==2.*
    - pandas-stubs ==2.*
    - python-dotenv ==0.21.*
    - requests ==2.*
    - requests-cache ==0.9.*
    - sqlalchemy ==2.*
    - tqdm ==4.*
    - types-requests ==2.*
    - typing-extensions ==4.*
    - yfinance <0.2.29

test:
  imports:
    - finagg
  commands:
    - pip check
    - finagg --help
  requires:
    - pip

about:
  home: https://github.com/theOGognf/finagg
  doc_url: https://theogognf.github.io/finagg/
  summary: Data aggregation with popular and free financial APIs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
