{% set name = "finagg" %}
{% set version = "1.0.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/finagg-{{ version }}.tar.gz
  sha256: 4de03419d764855f8a76cd78fb88989e5c9e6eace9dc07ac5613535e5155add2

build:
  entry_points:
    - finagg = finagg.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0
    - setuptools-scm >=5
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4 ==4.*
    - click ==8.*
    - pandas ==2.*
    - pandas-stubs ==2.*
    - python-dotenv ==0.21.*
    - requests ==2.*
    - requests-cache ==0.9.*
    - sqlalchemy ==2.*
    - tqdm ==4.*
    - types-requests ==2.*
    - typing-extensions ==4.*
    - yfinance <0.2.29

test:
  imports:
    - finagg
  commands:
    - pip check
    - finagg --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/theOGognf/finagg
  doc_url: https://theogognf.github.io/finagg/
  summary: Data aggregation with popular and free financial APIs.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
